//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleAppMVC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VehicleAppMVCEntities : DbContext
    {
        public VehicleAppMVCEntities()
            : base("name=VehicleAppMVCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Cost> Costs { get; set; }
        public virtual DbSet<Fuel> Fuels { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
    }
}
