//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleAppMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cost
    {
        public int CostID { get; set; }
        public int VehicleID { get; set; }
        public int CostTitle { get; set; }
        public System.DateTime CostDate { get; set; }
        public int CostOdometerMileage { get; set; }
        public double CostRunningCost { get; set; }
        public string StripeToken { get; set; }
    
        public virtual Vehicle Vehicle { get; set; }
    }
}
