//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleAppMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fuel
    {
        public int FuelID { get; set; }
        public int VehicleID { get; set; }
        public System.DateTime FuelDate { get; set; }
        public int FuelOdometerMileage { get; set; }
        public int FuelQuantity { get; set; }
        public double FuelUnitPrice { get; set; }
        public bool FuelPartialFill { get; set; }
        public string StripeToken { get; set; }
    
        public virtual Vehicle Vehicle { get; set; }
    }
}
