//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleAppMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int NotificationID { get; set; }
        public string ApplicationUserId { get; set; }
        public int NotificationTitle { get; set; }
        public int NotificationType { get; set; }
        public System.DateTime NotificationDate { get; set; }
        public System.DateTime NotificationSendDate { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
