// <auto-generated />
namespace VehicleAppMVC.Migrations.ApplicationDbMigration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update5));
        
        string IMigrationMetadata.Id
        {
            get { return "201704181918222_Update 5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
